-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgaJI4epyZM2Zw9SC0
mwqtCLEyktouWPGYXl4hBtueWHigCgYIKoZIzj0DAQehRANCAARfyNjbJp2rUo6V
ODJ/JpUUU7QQhEb1DWSndlaLbUaa1NJgEmDTuwxTaZyJC0d/gnhRpOP0pfs6umcX
8IWbT3Yq
-----END PRIVATE KEY-----